### ISSUE TITLE
UploadByFilename no connPool can be use

### ISSUE THREAD

**Issue by tgb12198** [tedcy/fdfs_client#4]
在Windows平台调用读取配置文件，配置文件貌似必须用utf-8才能被读取到，还有个问题请教教下，我在Windows平台使用报这个错误：API server listening at: 127.0.0.1:53055
UploadByFilename no connPool can be use ，我调试看了下。
line, err := reader.ReadString('\n')
line = strings.TrimSuffix(line, "\n")

这里是不是应该用\r\n呢

**Comment by tgb12198** [comment]
windows下开发读取不到配置文件

**Comment by tedcy** [comment]
嗯，当时只做了linux适配

**Comment by tgb12198** [comment]
API server listening at: 127.0.0.1:49990
read tcp 192.168.3.133:49997->192.168.3.139:23000: wsarecv: An existing connection was forcibly closed by the remote host.
我用windows中调用往Linux服务器上传文件  一直都报这个错   不知道咋回事   麻烦帮我看看
谢谢了

**Comment by tedcy** [comment]
解决了是吧？
