### ISSUE TITLE
有个问题请教下

### ISSUE THREAD

**Issue by tgb12198** [tedcy/fdfs_client#5]
API server listening at: 127.0.0.1:49703
TrackerTask RecvHeader recv resp status 28 != 0
Debugger finished with exit code 0

请问这个报错是什么问题

**Comment by tedcy** [comment]
这个是fastdfs的报错，最近余大又开始维护fastdfs了，你可以加群咨询。
fastdfs用的是linux的errno.h头文件。
errno -ls可以看到错误码对应信息。
28是磁盘满了。
