### ISSUE TITLE
fdfs client.conf文件中字段提取有问题

### ISSUE THREAD

**Issue by cp-zero** [tedcy/fdfs_client#6]
conn_pool.go中会判断client.conf中maxConns的值，实际上该字段并不存在，导致下面的判断成立，返回error信息
if maxConns < MAXCONNS_LEAST {
		return nil, fmt.Errorf("too little maxConns < %d", MAXCONNS_LEAST)
	}

**Comment by tedcy** [comment]
这个项目的读取配置文件的方式比较简单。
如果用本项目附带的fdfs.conf则没有问题

**Comment by tedcy** [comment]
`go test -v -test.run TestConfig`
你可以用新提交的单元测试，把你的client.conf改为fdfs.conf测试一下
